from typing import Any

class TextResult:
    text: str
    detected_source_lang: str

    def __init__(self, text: str, detected_source_lang: str) -> None: ...

class Translator:
    def __init__(self, auth_key: str, **kwargs: Any) -> None: ...
    def translate_text(
        self, text: str | list[str], target_lang: str, source_lang: str | None = None, **kwargs: Any
    ) -> TextResult | list[TextResult]: ...
    def get_usage(self) -> dict[str, Any]: ...
    def get_source_languages(self) -> list[dict[str, str]]: ...
    def get_target_languages(self) -> list[dict[str, str]]: ...
    def close(self) -> None: ...
