from typing import Any, TypeVar

T = TypeVar("T")

class Client:
    def __init__(self, src: str, hf_token: str | None = None) -> None: ...
    def predict(self, *args: Any, api_name: str | None = None, fn_index: int | None = None) -> Any: ...
    def submit(self, *args: Any, api_name: str | None = None, fn_index: int | None = None) -> Any: ...
    def view_api(self) -> str: ...
    def reset_session(self) -> None: ...
    def close(self) -> None: ...
